# dsh 托管子域 —— HTTP 验证临时配置(certbot 用,之后替换为完整配置)
server {
    listen 80;
    server_name u1.dsh.cbnac.com u2.dsh.cbnac.com u3.dsh.cbnac.com;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}